### ISSUE TITLE
Logging: Verified fields not logged

### ISSUE THREAD

**Issue by steentje34** [redcapuzgent/verify_all#2]
In the Logging functionality, fields that were verified manually are logged as follows:
![image](https://user-images.githubusercontent.com/29727779/56902703-1f5a5680-6a9b-11e9-9fd1-41209fb39a9a.png)

However, fields that were verified using the Verify all button are not logged.

**Comment by denshade** [comment]
Fixed in cdb1a0cee2ef3ad083c34e4304051ad84c57cb4f.
