### ISSUE TITLE
Logging: 'Verify all fields' does not provide full logging support (related to #3)

### ISSUE THREAD

**Issue by targetpharma** [redcapuzgent/verify_all#3]
When manually verifying a single field, the audit log includes not only the record id, but also the event and field information:

![image](https://user-images.githubusercontent.com/20141935/56989646-f3090d80-6b60-11e9-9301-9eed98cb10a8.png)

The 'Verify all fields' action only includes the record.

![image](https://user-images.githubusercontent.com/20141935/56989663-fbf9df00-6b60-11e9-9f74-3eeac460f1e9.png)

I believe I have a fix that I will try to include as a PR.

**Comment by targetpharma** [comment]
Created a PR: https://github.com/redcapuzgent/verify_all/pull/5

**Comment by denshade** [comment]
Thanks, #5 is merged.
